parameters:
- name: environment
  type: string
- name: project
  type: string
- name: workload
  type: string
- name: secretNames
  type: object
  default: {}

jobs:
- deployment: Deploy
  workspace:
    clean: all
  displayName: Deploy to ${{parameters.environment}}
  environment: '${{ parameters.environment }}'
  variables:
    - group: '${{parameters.workload}}-${{parameters.environment}}'
    - template: '../../templates/variables/${{parameters.environment}}.yml'
    - template: '../../${{ parameters.project }}/deploy/variables/main.yml'
      parameters:
        environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - task: AzureCLI@2
          displayName: 'Deploy main.bicep'
          ${{ if ne(length(parameters.secretNames), 0) }}:
            env: ${{ parameters.secretNames }}
          inputs:
            azureSubscription: '${{ variables.ServiceConnection }}'
            scriptType: pscore
            scriptLocation: inlineScript
            workingDirectory: '$(Pipeline.Workspace)/drop'
            inlineScript: |
              $ErrorActionPreference = "Stop"
              Set-PSDebug -Trace 1
              $suffix = (Get-Date -AsUTC).ToString('yyyyMMdd-HHmmss')
              $prefix = "${{parameters.workload}}"
              az deployment group create --resource-group "${{ variables.ResourceGroup }}" --template-file main.bicep --parameters main.bicepparam --name "${prefix}-${suffix}"
