services:
  cosmos:
    pull_policy: always
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    restart: unless-stopped
    ports:
    - "8081:8081"
    - "10250-10255:10250-10255"
    volumes:
    - cosmos-data:/tmp/cosmos/:rw
    environment:
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: true
volumes:
  cosmos-data:
