packages:
  - apps/*
  - packages/*
  - infrastructure
  - tools/*
  - build

overrides:
  '@apollo/server@>=5.0.0 <5.4.0': '>=5.4.0'
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  '@sveltejs/kit@>=2.19.0 <=2.49.4': '>=2.49.5'
  '@sveltejs/kit@>=2.49.0 <=2.49.4': '>=2.49.5'
  '@sveltejs/kit@>=2.49.0 <=2.52.1': '>=2.52.2'
  '@sveltejs/kit@>=2.49.0 <=2.53.2': '>=2.53.3'
  ajv@<6.14.0: '>=6.14.0'
  body-parser@>=2.2.0 <2.2.1: '>=2.2.1'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  cookie@<0.7.0: '>=0.7.0'
  devalue@<=5.6.2: '>=5.6.3'
  devalue@>=5.1.0 <5.6.2: '>=5.6.2'
  devalue@>=5.3.0 <=5.6.1: '>=5.6.2'
  diff@>=4.0.0 <4.0.4: '>=4.0.4'
  diff@>=6.0.0 <8.0.3: '>=8.0.3'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  h3@<=1.15.4: '>=1.15.5'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  jws@<3.2.3: '>=3.2.3'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  minimatch@<3.1.3: '>=3.1.3'
  minimatch@<3.1.4: '>=3.1.4'
  minimatch@>=10.0.0 <10.2.1: '>=10.2.1'
  minimatch@>=10.0.0 <10.2.3: '>=10.2.3'
  minimatch@>=5.0.0 <5.1.7: '>=5.1.7'
  minimatch@>=5.0.0 <5.1.8: '>=5.1.8'
  minimatch@>=9.0.0 <9.0.6: '>=9.0.6'
  minimatch@>=9.0.0 <9.0.7: '>=9.0.7'
  node-forge@<1.3.2: '>=1.3.2'
  qs@<6.14.1: '>=6.14.1'
  qs@>=6.7.0 <=6.14.1: '>=6.14.2'
  rollup@>=4.0.0 <4.59.0: '>=4.59.0'
  serialize-javascript@<=7.0.2: '>=7.0.3'
  sha.js@<=2.4.11: '>=2.4.12'
  svelte@<=5.51.4: '>=5.51.5'
  svelte@<=5.53.4: '>=5.53.5'
  svelte@>=5.39.3 <5.51.5: '>=5.51.5'
  tar@<7.5.7: '>=7.5.7'
  tar@<7.5.8: '>=7.5.8'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
  undici@<6.23.0: '>=6.23.0'
  vite@>=6.0.0 <=6.3.5: '>=6.3.6'
  vite@>=6.0.0 <=6.4.0: '>=6.4.1'
