packages:
  - apps/*
  - packages/*
  - infrastructure
  - tools/*
  - build

overrides:
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  cookie@<0.7.0: '>=0.7.0'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  jws@<3.2.3: '>=3.2.3'
  node-forge@<1.3.2: '>=1.3.2'
  sha.js@<=2.4.11: '>=2.4.12'
