parameters:
- name: environment
  type: string
- name: project
  type: string
- name: workload
  type: string

variables:
- template: '../variables/main.yml'
  parameters:
    environment: ${{ parameters.environment }}
    sandboxId: $(SandboxId)

jobs:
- template: ../../../templates/deploy/deploy-bicep.yml
  parameters:
    environment: ${{ parameters.environment }}
    project: ${{ parameters.project }}
    workload: ${{ parameters.workload }}
    secretNames: 
      MYSECRET: $(MYSECRET)
